USE [MushVsGrump]
GO

/****** Object:  Table [dbo].[WeaponType]    Script Date: 4/21/2016 4:57:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[WeaponType](
	[WeaponType] [varchar](12) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WeaponType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

